"""Add url column to Paper

Revision ID: b55311b2e035
Revises: 
Create Date: 2025-09-02 14:58:34.740844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55311b2e035'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('url', sa.String(length=2048), nullable=True))
    op.create_index(op.f('ix_papers_url'), 'papers', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_url'), table_name='papers')
    op.drop_column('papers', 'url')
    # ### end Alembic commands ###
